# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Admin.create!(
   email: 'weathes@weathes.com',
   password: 'weathes'
)


Prefecture.create(name: '北海道',name_prefecture: "Hokkaido")
Prefecture.create(name: '青森',name_prefecture: "Aomori-ken")
Prefecture.create(name: '岩手',name_prefecture: "Iwate")
Prefecture.create(name: '宮城',name_prefecture: "Miyagi-ken",)
Prefecture.create(name: '秋田',name_prefecture: "Akita")
Prefecture.create(name: '山形',name_prefecture: "Yamagata-ken")
Prefecture.create(name: '福島',name_prefecture: "Fukushima-ken")
Prefecture.create(name: '茨城',name_prefecture: "Ibaraki")
Prefecture.create(name: '栃木',name_prefecture: "Tochigi")
Prefecture.create(name: '群馬',name_prefecture: "Gunma-ken")
Prefecture.create(name: '埼玉',name_prefecture: "Saitama-ken")
Prefecture.create(name: '千葉',name_prefecture: "Chiba-ken")
Prefecture.create(name: '東京',name_prefecture: "Tokyo")
Prefecture.create(name: '神奈川',name_prefecture: "Kanagawa")
Prefecture.create(name: '新潟',name_prefecture: "Niigata-ken")
Prefecture.create(name: '富山',name_prefecture: "Toyama-ken")
Prefecture.create(name: '石川',name_prefecture: "Ishikawa-ken")
Prefecture.create(name: '福井',name_prefecture: "Fukui")
Prefecture.create(name: '山梨',name_prefecture: "Yamanashi")
Prefecture.create(name: '長野',name_prefecture: "Nagano-ken")
Prefecture.create(name: '岐阜',name_prefecture: "Gifu")
Prefecture.create(name: '静岡',name_prefecture: "Shizuoka")
Prefecture.create(name: '愛知',name_prefecture: "Aichi-ken")
Prefecture.create(name: '三重',name_prefecture: "Mie-ken")
Prefecture.create(name: '滋賀',name_prefecture: "Shiga")
Prefecture.create(name: '京都',name_prefecture: "kyoto")
Prefecture.create(name: '大阪',name_prefecture: "Osaka")
Prefecture.create(name: '兵庫',name_prefecture: "Hyōgo")
Prefecture.create(name: '奈良',name_prefecture: "Nara-ken")
Prefecture.create(name: '和歌山',name_prefecture: "Wakayama")
Prefecture.create(name: '鳥取',name_prefecture: "Tottori")
Prefecture.create(name: '島根',name_prefecture: "Shimane-ken")
Prefecture.create(name: '岡山',name_prefecture: "Okayama-ken")
Prefecture.create(name: '広島',name_prefecture: "Hiroshima-ken")
Prefecture.create(name: '山口',name_prefecture: "Yamaguchi")
Prefecture.create(name: '徳島',name_prefecture: "Tokushima-ken")
Prefecture.create(name: '香川',name_prefecture: "Kagawa-ken")
Prefecture.create(name: '愛媛',name_prefecture: "Ehime")
Prefecture.create(name: '高知',name_prefecture: "Kochi")
Prefecture.create(name: '福岡',name_prefecture: "Fukuoka")
Prefecture.create(name: '佐賀',name_prefecture: "Saga")
Prefecture.create(name: '長崎',name_prefecture: "Nagasaki")
Prefecture.create(name: '熊本',name_prefecture: "Kumamoto")
Prefecture.create(name: '大分',name_prefecture: "Oita")
Prefecture.create(name: '宮崎',name_prefecture: "Miyazaki")
Prefecture.create(name: '鹿児島',name_prefecture: "Kagoshima")
Prefecture.create(name: '沖縄',name_prefecture: "Okinawa")
